FROM matlab:r2020a

# Copiar el script .m dentro del contenedor
COPY script.m /app/script.m

# Establecer el directorio de trabajo
WORKDIR /app

# Definir un argumento para la ruta del script .m
ARG SCRIPT_PATH

# Copiar el script .m desde la ruta especificada
COPY $SCRIPT_PATH /app/script.m

# Ejecutar el script .m con Matlab
CMD ["matlab", "-nodisplay", "-r", "run('script.m');"]
