on:
  push:
    branches:
      - main
jobs:
  ejecucion-de-script:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout del repositorio
      uses: actions/checkout@v2
    - name: Build dockerfile
      working-directory: docker
      run: docker build -t mi-imagen -f dockerfile --build-arg SCRIPT_PATH=script.m .
